### ISSUE TITLE
Someting is wrong - open ticket

### ISSUE THREAD

**Issue by ricardoalvim-edu** [ladybirdweb/faveo-servicedesk-community#5]
Hi,

When I try open a ticket I can't open then, I had this page error: 
![faveo_ticket](https://cloud.githubusercontent.com/assets/13853627/25248462/bef1dac2-25e4-11e7-93fe-62b88ab7faae.PNG)

**Comment by kreatorcodes** [comment]
Can you explain what went wrong and how did you solve it?
